version: '2'
services:
  bbb-streamer:
    container_name: liveStreaming
    tty: true 
    shm_size: '2gb'
    build: 
        context: ./
    restart: unless-stopped
    ports:
      - 127.0.0.1:8001:8001
    volumes:
      - ./db:/usr/src/app/db
